common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: matt22
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: prngs_development

test:
  <<: *common
  database: prngs_test

production:
  <<: *common
  database: prngs_production