# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Source.create([
  { :name => "Pitchfork", :url => "http://pitchfork.com/", :kind => "Blog", :created_at => "2011-12-08 03:27:50", :updated_at => "2011-12-11 06:46:41", :feeds => ["http://feeds2.feedburner.com/PitchforkLatestNews"] },
  { :name => "Aquarium Drunkard", :url => "http://www.aquariumdrunkard.com/", :kind => "Blog", :created_at => "2011-12-08 03:29:40", :updated_at => "2011-12-11 06:46:43", :feeds => ["http://www.aquariumdrunkard.com/feed/", "http://www.aquariumdrunkard.com/feed/rss/", "http://www.aquariumdrunkard.com/feed/atom/"] },
  { :name => "Buzz Bands", :url => "http://buzzbands.la/", :kind => "Blog", :created_at => "2011-12-08 03:30:29", :updated_at => "2011-12-11 06:46:45", :feeds => ["http://buzzbands.la/feed/"] },
  { :name => "Invisible Oranges", :url => "http://www.invisibleoranges.com/", :kind => "Blog", :created_at => "2011-12-08 03:31:11", :updated_at => "2011-12-11 06:46:46", :feeds => ["http://www.invisibleoranges.com/feed/"] },
  { :name => "Kings of A&R", :url => "http://www.kingsofar.com/", :kind => "Blog", :created_at => "2011-12-08 03:31:42", :updated_at => "2011-12-11 06:46:47", :feeds => ["http://www.kingsofar.com/feed/", "http://www.kingsofar.com/feed/atom/", "http://kingsofar.com/?feed=rss2"] },
  { :name => "Rap Radar", :url => "http://rapradar.com/", :kind => "Blog", :created_at => "2011-12-08 03:32:28", :updated_at => "2011-12-11 06:46:48", :feeds => ["http://rapradar.com/feed/"] },
  { :name => "Stereogum", :url => "http://stereogum.com/", :kind => "Blog", :created_at => "2011-12-08 03:33:08", :updated_at => "2011-12-11 06:46:49", :feeds => ["http://feeds.feedburner.com/stereogum/cBYa"] },
  { :name => "FreeIndie", :url => "http://www.freeindie.com/", :kind => "Blog", :created_at => "2011-12-08 03:34:54", :updated_at => "2011-12-11 06:46:50", :feeds => ["http://www.freeindie.com/rss"] },
  { :name => "Bowlegs Music Review", :url => "http://www.bowlegsmusic.com/", :kind => "Blog", :created_at => "2011-12-08 03:35:40", :updated_at => "2011-12-11 06:46:52", :feeds => ["http://www.bowlegsmusic.com/feed/"] },
  { :name => "Fuck yeah! Go team!", :url => "http://fuckyeahgoteam.blogspot.com/index.html", :kind => "Blog", :created_at => "2011-12-08 03:36:13", :updated_at => "2011-12-11 06:46:53", :feeds => ["http://fuckyeahgoteam.blogspot.com/feeds/posts/default", "http://fuckyeahgoteam.blogspot.com/feeds/posts/default?alt=rss"] },
  { :name => "Prefix Magazine", :url => "http://www.prefixmag.com/", :kind => "Blog", :created_at => "2011-12-08 03:37:05", :updated_at => "2011-12-11 06:46:53", :feeds => ["http://www.prefixmag.com/feeds/reader/"] },
  { :name => "AudioCred", :url => "http://www.audiocred.com/", :kind => "Blog", :created_at => "2011-12-08 03:38:31", :updated_at => "2011-12-11 06:46:55", :feeds => ["http://www.audiocred.com/feed/"] },
  { :name => "Fuzzy Logic", :url => "http://www.logicfuzzy.com/", :kind => "Blog", :created_at => "2011-12-08 03:39:16", :updated_at => "2011-12-11 06:46:56", :feeds => ["http://www.logicfuzzy.com/feeds/posts/default", "http://www.logicfuzzy.com/feeds/posts/default?alt=rss"] },
  { :name => "Obscure Sound", :url => "http://obscuresound.com/", :kind => "Blog", :created_at => "2011-12-08 03:40:06", :updated_at => "2011-12-11 06:46:56", :feeds => ["http://feeds.feedburner.com/ObscureSound", "http://obscuresound.com/?feed=rss2"] },
  { :name => "The Fader", :url => "http://www.thefader.com/category/music/mp3-streams/", :kind => "Blog", :created_at => "2011-12-08 03:40:46", :updated_at => "2011-12-11 06:46:57", :feeds => ["http://www.thefader.com/feed/", "http://www.thefader.com/category/music/mp3-streams/feed/", "http://www.thefader.com/?feed=gigpress", "http://feeds.feedburner.com/TheFaderMagazine"] },
  { :name => "One Song A Day", :url => "http://www.1songday.com/", :kind => "Blog", :created_at => "2011-12-08 03:41:33", :updated_at => "2011-12-11 06:46:59", :feeds => ["http://feeds.feedburner.com/blogspot/oneaday"] },
  { :name => "Gorilla Vs. Bear", :url => "http://www.gorillavsbear.net/", :kind => "Blog", :created_at => "2011-12-08 03:42:30", :updated_at => "2011-12-11 06:47:00", :feeds => ["http://www.gorillavsbear.net/feed/"] },
  { :name => "Captain Obvious", :url => "http://www.thankscaptainobvious.net/", :kind => "Blog", :created_at => "2011-12-08 03:43:10", :updated_at => "2011-12-11 06:47:02", :feeds => ["http://www.thankscaptainobvious.net/feed/"] },
  { :name => "Consequence of Sound", :url => "http://consequenceofsound.net/", :kind => "Blog", :created_at => "2011-12-08 03:44:00", :updated_at => "2011-12-11 06:47:08", :feeds => ["http://consequenceofsound.net/feed/", "http://consequenceofsound.net/home/feed/", "http://consequenceofsound.net/category/cos-exclusive-features/festival-feed/"] },
  { :name => "treeswingers", :url => "http://treeswingers.com/", :kind => "Blog", :created_at => "2011-12-08 03:44:44", :updated_at => "2011-12-11 06:47:09", :feeds => ["http://treeswingers.com/feed/"] }
])


